

[allowlist]
paths = [
    '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket|xlsx|zip|ppt|pptx|exe|plist|bak|data|log|sqlite|db)$''',
    '''(go.mod|go.sum)$''',
    '''node_modules''',
    '''vendor''',
]

