
[allowlist]
paths = [
    '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket|csv|xlsx|ini|properties|proterty|csr|cer|der|p12|pem|zip|ppt|pptx|exe|toml|yaml|txt|xml|plist|config|cfg|sql|bak|data|log|json|sqlite|db|conf)$''',
    '''(go.mod|go.sum)$''',
    '''node_modules''',
    '''vendor''',
]

