
[allowlist]
paths = [
    '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket|csv|xlsx|ini|properties|proterty|csr|cer|der|p12|pem|zip|ppt|pptx|exe|toml|yaml|txt|m|xml|plist|config|cfg|sql|bak|data|log|json|sqlite|db|conf)$''',
    '''(go.mod|go.sum)$''',
    '''node_modules''',
    '''vendor''',
]

[[rules]]
description = "低长度凭证检出"
id = "generic-high-checkout-short-secret"
regex = '''(?i)(?:['|"|:|=| ]{1,3})((?i)[`*~%^$!&@#\w]{8,15})(?:[;|\)| |,|'|"|\n|\r|\s|\x60])'''
secretGroup = 1
entropy = 2.6
keywords = [
    "password","passwd","pwd",
    "secret",
    "access",
    "key","appkey",
    "user","usr",
    "login",
]