port: 80
gitleaks_exe_path: ./SecretDetect.exe
gitleaks_report_file: .gitleaks.json
TomlRule1: ./config/gitleaks-n-all-kill.toml
TomlRule2: ./config/gitleaks-all-kill.toml
exit-code: 0
save_to_local_path: ./upload/